### ISSUE TITLE
Process @RequestHeader Annotations

### ISSUE THREAD

**Issue by DarkAtra** [idealo/spring-endpoint-exporter#11]
Implement a parser for `@RequestHeader` annotations and export all headers as parameters in OpenAPI 3 format ([further details](https://swagger.io/docs/specification/describing-parameters/#header-parameters))

**Comment by mdube77** [comment]
@DarkAtra ready for review ;)

**Comment by DarkAtra** [comment]
top arbeit :D

**Comment by mdube77** [comment]
du meinst, ich hab mein gesellenstück erfolgreich abgeliefert 🤣
